EXECUTABLE_SERVER	:= tcp_server
EXECUTABLE_CLIENT := tcp_client

main: $(EXECUTABLE_CLIENT).cpp $(EXECUTABLE_SERVER).cpp
	g++ -g -Wall -std=c++17 -o $(EXECUTABLE_SERVER) $(EXECUTABLE_SERVER).cpp 
	g++ -g -Wall -std=c++17 -o $(EXECUTABLE_CLIENT) $(EXECUTABLE_CLIENT).cpp

clean:
	-rm $(EXECUTABLE_SERVER)
	-rm $(EXECUTABLE_CLIENT)

